- src/main/java/com/todayescape/config/SecurityConfig.java
hotfix/h2-console-access → develop
- h2 console 액세스를 위해 security config 파일을 작성했습니다.
로그인 시 h2 콘솔 잘 뜹니다!!
> Hotfix: h2 console access (#6)

- README.md
- settings.gradle
- src/main/java/com/nextroom/oescape/OEscapeApplication.java
- src/main/java/com/nextroom/oescape/config/SwaggerConfig.java
- src/main/java/com/nextroom/oescape/controller/TestController.java
- src/main/java/com/nextroom/oescape/domain/Hint.java
- src/main/java/com/nextroom/oescape/domain/Shop.java
- src/main/java/com/nextroom/oescape/domain/Theme.java
- src/main/java/com/nextroom/oescape/dto/BaseResponse.java
- src/main/java/com/nextroom/oescape/dto/DataResponse.java
- src/main/java/com/nextroom/oescape/exceptions/CustomException.java
- src/main/java/com/nextroom/oescape/exceptions/ErrorResponse.java
- src/main/java/com/nextroom/oescape/exceptions/GlobalExceptionHandler.java
- src/main/java/com/nextroom/oescape/exceptions/StatusCode.java
- src/test/java/com/nextroom/oescape/OEscapeApplicationTests.java
hotfix/modify-project-name → develop
- 프로젝트, 패키지명 모두 변경했습니다!
테스트 아직 없지만 빌드 잘 됩니다!
> Refactor: 프로젝트/패키지명 변경 (#8)

- appspec.yml
- build.gradle
- scripts/start.sh
- scripts/stop.sh
feature/deploy → develop
- 어플리케이션 실행/중단을 위한 bash script들을 작성했습니다.
- codedeploy가 식별하기 위한 appspec.yml 파일을 작성했습니다.
- plain 빌드 파일이 생성되지 않도록 설정을 추가했습니다.
테스트 없음!!
> [FEAT] 배포를 위한 스크림트, 설정 파일 작성

- src/main/java/com/nextroom/oescape/security/config/SecurityConfig.java
feature/cors → develop
- spring security에 cors 세팅 추가해주었습니다.
postman으로 헤더 넣고 테스트 해보았는데 잘됩니다~!
> [FEAT] cors 설정 추가

- src/main/java/com/nextroom/oescape/service/HintService.java
refactor/use-findById → develop
- getReferenceById -> findById 메서드로 대체했습니다.
- theme 가 존재하지 않는 경우의 NOTFOUND 에러 처리를 구현했습니다.
빌드, postman 테스트 정상 작동합니다!
> [REFACTOR] findById 적용 및 NOTFOUND 핸들링 구현 (#36)

- build.gradle
- src/main/java/com/nextroom/oescape/controller/AuthController.java
- src/main/java/com/nextroom/oescape/dto/AuthDto.java
- src/main/java/com/nextroom/oescape/exceptions/GlobalExceptionHandler.java
- src/main/java/com/nextroom/oescape/service/AuthService.java
Refactor/auth-error-handling → develop
- 로그인 시 발생할 수 있는 인증 에러에 대해 CustomException 으로 처리해주었습니다.
- 로그인/회원가입에 사용되는 요청 DTO에 validation을 구현했습니다.
- global exception handler에서 validation error를 처리해 응답으로 내려주도록 구현했습니다.
빌드, postman 테스트 모두 잘 동작 합니다!
> [REFACTOR] Auth 도메인 예외 처리 강화 (#34)

- src/main/java/com/nextroom/oescape/exceptions/GlobalExceptionHandler.java
refactor/auth-error-handling → develop
- requireNonNull 메서드가 중첩 사용되어 수정했습니다.
빌드, postman 테스트 모두 잘 동작 합니다!
> [CHORE] requireNonNull 중첩 사용 삭제

- src/main/java/com/nextroom/oescape/controller/ThemeController.java
- src/main/java/com/nextroom/oescape/domain/Theme.java
- src/main/java/com/nextroom/oescape/dto/ThemeDto.java
- src/main/java/com/nextroom/oescape/service/ThemeService.java
feature/theme-exception → develop
- 다양한 예외 경우를 예측하여 기존 대비 예외 처리를 강화하였습니다.
- 검증용 validate 메서드를 분리하여 하나의 메서드가 많은 기능을 하지 않도록 조치하였습니다.
- 기존에 분리되어 있던 테마 조회 로직을 하나로 합치면서 불필요하게 중복되던 코드를 제거하였습니다.
- Theme Entity에  Not Null 조건을 추가하였습니다.
- @Valid 어노테이션을 활용하여 Request 요청 값을 검증하였습니다.
> [REFACTOR] Theme 예외 처리 강화

- src/main/java/com/nextroom/oescape/controller/HintController.java
- src/main/java/com/nextroom/oescape/dto/HintDto.java
- src/main/java/com/nextroom/oescape/exceptions/GlobalExceptionHandler.java
- src/main/java/com/nextroom/oescape/exceptions/StatusCode.java
- src/main/java/com/nextroom/oescape/repository/HintRepository.java
- src/main/java/com/nextroom/oescape/service/HintService.java
refactor/hint-error-handling → develop
- hint api 요청의 validation 및 error response 를 구현했습니다.
- 힌트코드 4자리 제한 및 중복 방지
- 진행률 100 이하 음이 아닌 정수
- 상황 별 error response 구현했습니다..
postman 테스트 결과 이상 없습니다~!
> [REFACTOR] 힌트 예외 처리 강화

- src/main/java/com/nextroom/oescape/OEscapeApplication.java
- src/main/java/com/nextroom/oescape/domain/Hint.java
- src/main/java/com/nextroom/oescape/domain/Shop.java
- src/main/java/com/nextroom/oescape/domain/Theme.java
- src/main/java/com/nextroom/oescape/dto/AuthDto.java
- src/main/java/com/nextroom/oescape/dto/HintDto.java
- src/main/java/com/nextroom/oescape/dto/ThemeDto.java
- src/main/java/com/nextroom/oescape/service/AuthService.java
- src/main/java/com/nextroom/oescape/service/HintService.java
- src/main/java/com/nextroom/oescape/service/ThemeService.java
- src/main/java/com/nextroom/oescape/util/Timestamped.java
feature/add-column → develop (#41 #47)
- 업체명(name), 남은 힌트 갯수(hintLimit), 각 컬럼의 생성일, 수정일(createdAt, modifiedAt)을 추가 하였습니다.
- 업체명은 필수 입력 사항이고, 남은 힌트 갯수는 필수 입력 사항이 아닙니다.
- Timestamped 클래스를 모든 Entity에서 상속 받도록 구현하였습니다.
- 기획 변경으로 더 이상 사용하지 않는 hintTitle 컬럼을 제거하였습니다.
postman 테스트 결과 이상 없습니다~
> [FEAT] Database Column 추가 및 삭제

- src/main/java/com/nextroom/oescape/domain/Hint.java
- src/main/java/com/nextroom/oescape/dto/HintDto.java
- src/main/java/com/nextroom/oescape/dto/ThemeDto.java
- src/main/java/com/nextroom/oescape/service/HintService.java
- src/main/java/com/nextroom/oescape/service/ThemeService.java
refactor/dto-converting-method → develop
- 기존에 entity 내에서 dto로 변환시키는 메서드를 엔티티로부터 분리하여, dto 생성자를 통해 변환하도록 구현을 수정했습니다.
- builder 패턴을 통해 생성하던 response DTO 를 생성자를 통해 생성하도록 구현 방식을 통일했습니다.
> [REFACTOR] DTO 변환 메서드 구현

- src/main/java/com/nextroom/oescape/domain/Hint.java
- src/main/java/com/nextroom/oescape/domain/Shop.java
- src/main/java/com/nextroom/oescape/domain/Theme.java
feature/entity-column-condition → develop
- entity class 의 각 필드에 DB column 속성 및 조건을 설정해주었습니다.
postman 실행 결과 이상 없습니다. 
또, DB와 연결 후에도 무리없이 잘 되는 걸 확인했습니다!
> [FEAT] 엔티티 클래스 column 조건 설정

- src/main/java/com/nextroom/oescape/config/SwaggerConfig.java
feature/swagger → develop
- 배포 환경에 따라 Swagger에 다음과 같이 profile을 추가하였습니다.
Swagger 테스트 결과 이상 없습니다!
> [REFACTOR] Swagger profile 설정 

- src/main/java/com/nextroom/nextRoomServer/domain/Subscription.java
- src/main/java/com/nextroom/nextRoomServer/dto/SubscriptionDto.java
- src/main/java/com/nextroom/nextRoomServer/enums/SubscriptionPlan.java
- src/main/java/com/nextroom/nextRoomServer/service/SubscriptionService.java
feature/sub-api → feature/subscription
- Entity에서 subscribed_at 제거
- DTO에서 subscribed_at, modified_at 제거
- SubscriptionPlan에서 FREE 제거
- 이용권 정보 조회에서 토큰 검증 부분 제거
postman 테스트 결과 이상 없습니다.
> [FEAT] 구독 상태 세부 로직 변경

- src/main/java/com/nextroom/nextRoomServer/exceptions/StatusCode.java
- src/main/java/com/nextroom/nextRoomServer/security/ExceptionHandlerFilter.java
- src/main/java/com/nextroom/nextRoomServer/security/jwt/JwtFilter.java
feature/token-exception→ develop
- 요청에 토큰이 없는 경우, 200 응답이 아닌 400 에러를 전달할 수 있도록 변경하였습니다.
- 인증과 관련된 에러는 401(Unauthorized)로 status code를 변경하였습니다.
> [REFACTOR] 토큰 관련 예외 처리

- README.md
> [DOCS] README 수정

- src/main/java/com/nextroom/nextRoomServer/domain/Hint.java
- src/main/java/com/nextroom/nextRoomServer/domain/Shop.java
- src/main/java/com/nextroom/nextRoomServer/domain/Theme.java
- src/main/java/com/nextroom/nextRoomServer/dto/AuthDto.java
- src/main/java/com/nextroom/nextRoomServer/util/Timestamped.java
feature/register → develop
- 회원가입 dto에 매장 오픈 여부 boolean 변수 추가
- 매장 오픈하지 않았을 경우, 기본 매장명은 '오픈 예정 매장', 사유는 comment 컬럼에 저장
api 테스트 결과 이상 없습니다.
> [FEAT] 오픈 예정 매장 추가

- src/main/java/com/nextroom/nextRoomServer/dto/AuthDto.java
feature/typing-error → develop
- 오픈 예정 매장의 오타를 수정하였습니다.
테스트 이상 없습니다.
> [CHORE] 오픈 예정 매장 오타 수정

- src/main/java/com/nextroom/nextRoomServer/dto/AuthDto.java
- src/main/java/com/nextroom/nextRoomServer/repository/ShopRepository.java
- src/main/java/com/nextroom/nextRoomServer/service/AuthService.java
- src/main/java/com/nextroom/nextRoomServer/service/MailService.java
- src/main/java/com/nextroom/nextRoomServer/util/RandomCodeGenerator.java
feature/admin_code → develop
- Admin Code 기존 '00000'에서 랜덤 생성하는 것으로 변경
> [FEAT] Admin Code 랜덤 생성 추가

- .github/workflows/deploy-dev.yml
feature/deploy → develop
- AWS 계정 변경으로 인해 deploy.yml 파일을 수정합니다.
테스트가 필요합니다.
> [CI/CD] deploy-dev.yml 생성

- .github/workflows/deploy-dev.yml
feature/deploy → develop
- application.yml 파일이 변경되었습니다.
테스트가 필요합니다.
> [CI/CD] application.yml 파일 변경

- .github/workflows/deploy-prod.yml
- scripts/start.sh
feature/deploy → main
- NCP에서 AWS로 운영 서버를 이전합니다.
테스트가 필요합니다.
> [CI/CD] 운영 서버 CI/CD 설정

- scripts/start.sh
feature/code-deploy-variables → develop
- CodeDeploy에서 appspec.yml을 참고하여 start.sh 실행 시, profile을 주입하여 jar 파일을 구동 시킬 수 있도록 /etc/.profile.d/codedeploy.sh에 등록해둔 환경 변수를 사용하였습니다.
테스트를 위해 빠른 배포가 필요합니다.
> [CI/CD] CodeDeploy 환경변수 테스트

- scripts/start.sh
feature/code-deploy-variables → develop
- AWS Parameter store에 등록해둔 환경 변수가 작동하지 않아 이전 설정으로 돌려주었습니다.
다른 방법을 찾아봐야 할 것 같습니다😥
> [CI/CD] CodeDeploy 환경변수 원복

- .github/workflows/deploy-dev.yml
feature/new-subscription → develop
- Githu Actions workflow를 수정하였습니다.
> [CI/CD] workflow 수정

- src/main/java/com/nextroom/nextRoomServer/controller/ThemeController.java
- src/main/java/com/nextroom/nextRoomServer/dto/ThemeDto.java
- src/main/java/com/nextroom/nextRoomServer/service/ThemeService.java
feature/add-theme → develop
- 테마 등록 시, 등록된 theme id를 response로 반환 하도록 수정하였습니다.
> [CHORE] 테마 등록 API Response 변경

- src/main/java/com/nextroom/nextRoomServer/controller/PaymentController.java
- src/main/java/com/nextroom/nextRoomServer/dto/SubscriptionDto.java
- src/main/java/com/nextroom/nextRoomServer/service/PaymentService.java
- src/main/java/com/nextroom/nextRoomServer/service/SubscriptionService.java
- src/main/java/com/nextroom/nextRoomServer/service/ThemeService.java
- src/main/java/com/nextroom/nextRoomServer/util/inapp/AndroidPurchaseUtils.java
- src/main/resources/logback-spring.xml
- src/test/java/com/nextroom/nextRoomServer/util/CommonObjectMapperTest.java
feature/monitor → develop
- 로그레벨 변경, Dev/Prod 환경 롤링 로그 파일 드랍하도록 설정
- rtdn verify 시 구독 정보 전부 로깅하도록 수정
테스트 결과를 적어주세요!
> [FEAT] Logback 추가 

- src/main/resources/logback-spring.xml
- 리뷰어가 확인하기 쉽도록 변경된 내용을 상세히 적어주세요!
테스트 결과를 적어주세요!
> [FIX] modify log path

- src/main/java/com/nextroom/nextRoomServer/dto/HintDto.java
- src/main/java/com/nextroom/nextRoomServer/service/HintService.java
- 리뷰어가 확인하기 쉽도록 변경된 내용을 상세히 적어주세요!
테스트 결과를 적어주세요!
> [FIX] 힌트코드 변경된 경우만 중복 검증

- src/main/resources/logback-spring.xml
- 리뷰어가 확인하기 쉽도록 변경된 내용을 상세히 적어주세요!
테스트 결과를 적어주세요!
> Dev log level 변경

- src/main/java/com/nextroom/nextRoomServer/util/inapp/AndroidPurchaseUtils.java
- 리뷰어가 확인하기 쉽도록 변경된 내용을 상세히 적어주세요!
테스트 결과를 적어주세요!
> [TEST] notification 테스트 검증 로직 주석

- src/main/java/com/nextroom/nextRoomServer/controller/ThemeController.java
- src/main/java/com/nextroom/nextRoomServer/domain/Theme.java
- src/main/java/com/nextroom/nextRoomServer/dto/ThemeDto.java
- src/main/java/com/nextroom/nextRoomServer/service/HintService.java
- src/main/java/com/nextroom/nextRoomServer/service/ThemeService.java
- src/main/java/com/nextroom/nextRoomServer/util/aws/S3Component.java
- timer 관련 API 추가
- 수정 기능은 삭제 후 재추가로 정의되어있어 put 은 생성하지 않았습니다
- 이후 다른 종류의 image 가 추가될 지 몰라 timer prefix 로 지정했습니다
- theme domain 의 의존도를 분리하기 위해 service 를 생성했습니다
테스트 결과를 적어주세요!
> [FEAT] 타이머 이미지 기능 추가

- src/main/java/com/nextroom/nextRoomServer/exceptions/StatusCode.java
- src/main/java/com/nextroom/nextRoomServer/util/inapp/AndroidPurchaseUtils.java
feature/validate-acknowledgement → develop
- 구독 결제 시, 어뷰징 방지를 위해 이미 승인된 상품은 예외 처리 하였습니다.
배포 후 테스트가 필요합니다.
> [FEAT] 구독 결제 시, 이미 승인된 상품은 예외처리

- src/main/java/com/nextroom/nextRoomServer/util/inapp/AndroidPurchaseUtils.java
feature/validate-acknowledgement → develop
- ACKNOWLEDGEMENT_STATE_ACKNOWLEDGED 상수 처리 하였습니다.
https://github.com/Next-Room/NextRoom-be/pull/156#discussion_r1899080433
> [CHORE] ACKNOWLEDGEMENT_STATE_ACKNOWLEDGED 상수로 변경

- src/main/java/com/nextroom/nextRoomServer/exceptions/StatusCode.java
- src/main/java/com/nextroom/nextRoomServer/util/inapp/AndroidPurchaseUtils.java
temp-branch → main
- https://github.com/Next-Room/NextRoom-be/pull/156
- https://github.com/Next-Room/NextRoom-be/pull/157
> [RELEASES] 구독 결제 시, acknowledgement 검증 로직 추가

- src/main/java/com/nextroom/nextRoomServer/domain/Banner.java
- src/main/java/com/nextroom/nextRoomServer/dto/BannerDto.java
feature/banner → develop
- 배너 조회 api에 배너용 이미지 url을 추가하였습니다
> [FEAT] 배너 api에 이미지 추가

- src/main/java/com/nextroom/nextRoomServer/controller/ThemeController.java
- src/main/java/com/nextroom/nextRoomServer/dto/ThemeDto.java
docs/swagger → develop
- `getAllThemeIds()` 메서드를 DTO의 필드로 간주하여 JSON 응답에 포함 시키는 버그가 발생하였습니다. `@Schema(hidden = true)` 사용하여 Swagger 문서에서 숨김 처리 하였습니다.
- 테마 조회 api의 response 응답이 Swagger 문서에 표현되도록 수정 하였습니다.
> [DOCS] Swagger 문서 수정

- src/main/java/com/nextroom/nextRoomServer/repository/BannerRepository.java
- src/main/java/com/nextroom/nextRoomServer/service/BannerService.java
feature/banner-orderby → develop
- 배너 리스트 조회 정렬을 최신순으로 수정하였습니다.
> [CHORE] 배너 최신순 정렬

- src/test/java/com/nextroom/nextRoomServer/util/AndroidPurchaseUtilsTest.java
- src/test/java/com/nextroom/nextRoomServer/util/TimestampedTest.java
test/subscription → develop
- 구독 관련 간단한 테스트를 추가하였습니다.
테스트 이상 없습니다.
> [TEST] 구독 관련 테스트 추가

- build.gradle
- src/main/java/com/nextroom/nextRoomServer/controller/AuthController.java
- src/main/java/com/nextroom/nextRoomServer/domain/Shop.java
- src/main/java/com/nextroom/nextRoomServer/dto/AuthDto.java
- src/main/java/com/nextroom/nextRoomServer/repository/ShopRepository.java
- src/main/java/com/nextroom/nextRoomServer/security/TokenProvider.java
- src/main/java/com/nextroom/nextRoomServer/service/AuthService.java
- src/main/java/com/nextroom/nextRoomServer/service/CustomUserDetailsService.java
- src/main/java/com/nextroom/nextRoomServer/service/MailService.java
- src/main/java/com/nextroom/nextRoomServer/util/oauth2/GoogleClient.java
- src/main/java/com/nextroom/nextRoomServer/util/oauth2/GoogleClientConfig.java
feature/google-login → develop
- 구글 로그인 api가 추가되었습니다.
- 웹은 Authorization Code를, 앱은 Id Token을 받아 검증하는 형태로 구현하였습니다.
클라이언트 연결 후 테스트가 필요합니다.
> [FEAT] 구글 로그인 추가

- src/main/java/com/nextroom/nextRoomServer/domain/Shop.java
- src/main/java/com/nextroom/nextRoomServer/dto/AuthDto.java
- src/main/java/com/nextroom/nextRoomServer/service/AuthService.java
feature/google-login → develop
- 구글 로그인의 응답 구조를 변경하였습니다.
> [REFACTOR] 구글 로그인 응답 구조 변경

- src/main/java/com/nextroom/nextRoomServer/domain/Shop.java
- src/main/java/com/nextroom/nextRoomServer/dto/AuthDto.java
feature/google-login → develop
- 넥스트룸 가입 절차 진행시, 업데이트 정보 수신 동의 여부를 함께 받아 저장합니다.
> [FEAT] 업데이트 정보 수신 동의 여부 저장

- src/main/java/com/nextroom/nextRoomServer/controller/AuthController.java
- src/main/java/com/nextroom/nextRoomServer/dto/AuthDto.java
feature/google-login → develop
- swagger에 request의 각 필드 설명과, nullable 관련 정보를 추가하였습니다.
> [DOCS] 구글 로그인 관련 swagger 문서 수정

- src/main/java/com/nextroom/nextRoomServer/dto/AuthDto.java
feature/password → develop
- 비밀번호 조건 변경에 따라 정규식을 수정하였습니다.
- 기존: 대문자, 소문자, 숫자, 기호 조합 8자 이상
- 변경: 숫자 혹은 기호 중 1개 이상 포함 8자 이상
> [CHORE] 비밀번호 조건 변경
