src/main/java/com/nextroom/oescape/controller/ThemeController.java
src/main/java/com/nextroom/oescape/domain/Theme.java
src/main/java/com/nextroom/oescape/exceptions/StatusCode.java
src/main/java/com/nextroom/oescape/repository/ThemeRepository.java
src/main/java/com/nextroom/oescape/service/ThemeService.java
src/test/java/com/nextroom/oescape/service/ThemeServiceTest.java

feature/theme → develop
- 테마 수정/삭제를 구현하였습니다.
- Service 계층 메서드가 변경되어 테스트 코드도 수정해주었습니다.
- 자주 사용하는 Status Code를 추가하였습니다.
Shop Entity가 없어 API 테스트를 진행하지 못했습니다.
현재 테스트 가능한 API는 '테마 등록' 입니다.
`POST /api/v1/theme` 로 다음과 같이 요청을 보내면 응답이 오는 걸 확인했습니다.
```json
{
"title":"테마 제목",
"timeLimit":70
}
```

[FEAT] Theme API 구현

---

src/main/java/com/nextroom/oescape/dto/AuthDto.java
src/main/java/com/nextroom/oescape/service/AuthService.java

hotfix/constructor → develop
- Builder 사용 시 모든 필드를 포함하는 생성자가 필요합니다. @AllArgsConstructor 를 추가하였습니다.
- ObjectMapper가 내부적으로 Json을 Java로 변환할 때 기본 생성자가 필요합니다. @NoArgsConstructor 를 추가하였습니다.
- final 필드가 있을 시 (force = true) 옵션을 통해 강제 초기화를 합니다.

[FIX] SignUpRequestDto 객체 생성이 안되던 문제 해결

---

src/main/java/com/nextroom/oescape/controller/AuthController.java
src/main/java/com/nextroom/oescape/controller/HintController.java
src/main/java/com/nextroom/oescape/controller/ThemeController.java
src/main/java/com/nextroom/oescape/dto/HintDto.java
src/main/java/com/nextroom/oescape/security/config/SecurityConfig.java

feature/swagger → develop
- TestController를 참고하여 모든 Controller에 Swagger 관련 어노테이션을 추가하였습니다.
- Swagger는 다음의 주소로 접속 가능합니다. `{url}/swagger-ui/index.html`
postman 테스트 결과 이상 없습니다~

[REFACTOR] Controller에 Swqgger 어노테이션 추가

---

src/main/java/com/nextroom/oescape/controller/AuthController.java
src/main/java/com/nextroom/oescape/controller/HintController.java
src/main/java/com/nextroom/oescape/controller/ThemeController.java
src/main/java/com/nextroom/oescape/exceptions/StatusCode.java
src/main/java/com/nextroom/oescape/security/SecurityUtil.java
src/main/java/com/nextroom/oescape/service/CustomUserDetailsService.java
src/main/java/com/nextroom/oescape/service/HintService.java
src/main/java/com/nextroom/oescape/service/ThemeService.java

feature/shop-auth → develop
- hint, theme service 내에서도 업체를 검증하기 위해 인증 정보를 통해 검증하는 로직을 구현했습니다.
postman 기반 명세 내 api 모두 잘 동작합니다.

[FEAT] hint/theme api 내 shop 검증 로직 구현

---

src/main/java/com/nextroom/oescape/controller/ThemeController.java
src/main/java/com/nextroom/oescape/exceptions/StatusCode.java
src/main/java/com/nextroom/oescape/security/config/SecurityConfig.java
src/main/java/com/nextroom/oescape/service/ThemeService.java

hotfix/android-auth → develop
- theme, hint의 get method 인증 면제를 통해 안드로이드에서 토큰 없이 접근할 수 있도록 구현했습니다.
- 안드로이드에서 토큰 없이 theme 조회할 수 있도록 분기 로직을 구현했습니다.
postman으로 토큰 없이 테스트 진행했고, 잘 동작하는것 확인했습니다!

[FIX] android 인증 면제

---

src/main/java/com/nextroom/oescape/controller/AuthController.java
src/main/java/com/nextroom/oescape/dto/AuthDto.java

feature/apply-password → develop
- password를 admin code로 사용했던 기존 로직을 수정하여, 분리해서 각각 사용할 수 있도록 구현했습니다.
- password validation을 구현했습니다.
postman 실행 결과 validation도 모두 잘 동작하고 잘 됩니다~!

[FEAT] 패스워드 로직 구현

---

src/main/java/com/nextroom/oescape/dto/AuthDto.java
src/main/java/com/nextroom/oescape/dto/TokenDto.java
src/main/java/com/nextroom/oescape/repository/ShopRepository.java
src/main/java/com/nextroom/oescape/service/AuthService.java

feature/login-response → develop
- LoginResponseDto와 TokenDto를 분리하여 비즈니스 로직에 유연하게 대처할 수 있도록 리팩토링 하였습니다.
- 로그인 성공 시 shopName을 확인할 수 있습니다.

[REFACTOR] Login 성공 응답에 shopName 추가

---

src/main/java/com/nextroom/oescape/exceptions/GlobalExceptionHandler.java
src/main/java/com/nextroom/oescape/exceptions/StatusCode.java
src/main/java/com/nextroom/oescape/security/ExceptionHandlerFilter.java
src/main/java/com/nextroom/oescape/security/SecurityUtil.java
src/main/java/com/nextroom/oescape/security/TokenProvider.java
src/main/java/com/nextroom/oescape/security/config/SecurityConfig.java
src/main/java/com/nextroom/oescape/service/AuthService.java

feature/token-exception-handling → develop
- security filter chain 내의 exception 을 handling 할 수 있는 filterChain 을 새로 정의하고 구현했습니다.
- 상황에 맞지 않는 Exception 정의를 수정했습니다.
postman 실행 이상 없이 이제 security 로직 내 에러도 응답으로 잘 내려줍니다!

[FIX] Security 로직 내 예외 처리 구현

---

src/main/java/com/nextroom/oescape/security/ExceptionHandlerFilter.java

hotfix/token-200-error → develop
- global exception handler 에서 처리하지 않는 security filter 내 exception handler 에서 응답 코드를 설정해주지 않아 발생하는 응답 코드 에러를 수정했습니다.
테스트 결과 응답 코드 문제없이 잘 반환합니다.

[HOTFIX] 토큰 검증 관련 에러 시 잘못된 응답 코드 수정

---

src/main/java/com/nextroom/nextRoomServer/controller/SubscriptionController.java
src/main/java/com/nextroom/nextRoomServer/domain/Shop.java
src/main/java/com/nextroom/nextRoomServer/domain/Subscription.java
src/main/java/com/nextroom/nextRoomServer/dto/SubscriptionDto.java
src/main/java/com/nextroom/nextRoomServer/enums/EnumModel.java
src/main/java/com/nextroom/nextRoomServer/enums/SubscriptionPlan.java
src/main/java/com/nextroom/nextRoomServer/enums/SubscriptionStatus.java
src/main/java/com/nextroom/nextRoomServer/enums/UserStatus.java
src/main/java/com/nextroom/nextRoomServer/repository/SubscriptionRepository.java
src/main/java/com/nextroom/nextRoomServer/service/SubscriptionService.java

feature/sub-api → feature/subscription
- 기존 ManyToOne이었던 Shop과 Subscription의 관계를 OneToOne으로 변경
- 구독 관련 Enum 정의
- SubscriptionStatus(구글 기준 구독 상태)
- UserStatus(프로덕트 기준 유저 상태)
- SubscriptionPlan(구독 요금제)
- 구독 관련 API 구현
- 마이페이지에서 필요한 API
- 유저 상태 API (테마 선택 페이지)
- 이용권 정보 API (이용권 정보 페이지)
- 안드로이드와의 빠른 테스트를 위해 핵심 로직 먼저 구현하였습니다.
Service단의 예외 처리는 추후 진행하겠습니다.
Postman 테스트 결과 이상 없습니다!

[FEAT] 구독 관련 API 구현

---

src/main/java/com/nextroom/nextRoomServer/dto/AuthDto.java
src/main/java/com/nextroom/nextRoomServer/exceptions/StatusCode.java
src/main/java/com/nextroom/nextRoomServer/security/TokenProvider.java

feature/refresh-token → develop
- ReissueRequestDto에 생성자 추가
- Token 만료 응답 코드 407로 변경
- Token 유효 기간 변경
- Access Token : 2시간
- Refresh Token : 14일

[REFACTOR] Refresh Token으로 Token 재발급 로직 재정비

---

src/main/java/com/nextroom/nextRoomServer/controller/HintController.java
src/main/java/com/nextroom/nextRoomServer/controller/ThemeController.java
src/main/java/com/nextroom/nextRoomServer/service/HintService.java
src/main/java/com/nextroom/nextRoomServer/service/ThemeService.java

feature/android-api → develop
- 테마 조회 API 와 힌트 조회 API의 인가 방식을 AdminCode가 아닌 토큰 방식으로 변경하면서 AdminCode 인가 로직을 삭제하였습니다.
- ThemeService의 validate 관련 메서드들의 이름만 보았을 때 객체를 리턴한다는 행위를 예측하기 어렵다는 의견(https://github.com/Next-Room/NextRoom-be/pull/43#discussion_r1276602700) 에 따라 get으로 메서드 이름을 변경하였습니다. (ex. validateShop → getShop)
테스트 결과, 토큰이 없는 요청에 200 응답이 오는 걸 확인했습니다.
해당 이슈(#39)는 추후 처리하겠습니다.

[REFACTOR] 안드로이드용 API 삭제

---

src/main/java/com/nextroom/nextRoomServer/dto/SubscriptionDto.java
src/main/java/com/nextroom/nextRoomServer/enums/EnumModel.java
src/main/java/com/nextroom/nextRoomServer/enums/SubscriptionPlan.java
src/main/java/com/nextroom/nextRoomServer/security/config/SecurityConfig.java
src/main/java/com/nextroom/nextRoomServer/service/SubscriptionService.java

feature/sub-api → develop
- 구독 API 서버 배포 후, 클라이언트 피드백에 따라 다음과 같이 변경합니다.
- 구독 상품 고유 id 추가 (String 타입)
- API 응답 시, SubscriptionPlan 키 제외
- 토큰 없이 요청 가능 하도록 구현
- 구독 plan 이름 영어에서 한글로 변경
- **추가+)** SecurityConfig 변경 후 이전에 해결했던 이슈(#39)가 다시 발생하는 것을 확인했습니다. 이전 상태로 돌려놨고, 추후 구독 상태에 따른 권한 설정 시 처리 할 예정입니다.

[REFACTOR] 구독 요금제 API 수정

---

src/main/java/com/nextroom/nextRoomServer/domain/Subscription.java
src/main/java/com/nextroom/nextRoomServer/service/AuthService.java
src/main/java/com/nextroom/nextRoomServer/service/SubscriptionService.java
src/main/java/com/nextroom/nextRoomServer/util/Timestamped.java

feature/free-status → develop
- 회원 가입 시, 구독 정보(무료 체험) 함께 생성 되도록 구현하였습니다.
- 이 때 생성 되는 구독 정보는 **FREE** status와 **MINI** plan을 갖습니다.
- 30일 무료체험 → 유예 → 유예 만료로 진행되는 상태 변경 로직을 구현하였습니다.
- userStatus 요청 시, 해당 유저의 status와 expiryDate를 고려하여 상태를 변경합니다.
- 기존 정책대로 유예 만료 시 데이터 삭제를 구현하였으나, 추후 변동 사항이 생길 경우를 대비하여 현재 주석 처리 해 둔 상태입니다.
postman 테스트 결과 이상 없습니다.

[FEAT] 30일 무료체험 구현

---

src/main/java/com/nextroom/nextRoomServer/enums/EnumModel.java
src/main/java/com/nextroom/nextRoomServer/enums/SubscriptionPlan.java
src/main/java/com/nextroom/nextRoomServer/exceptions/StatusCode.java
src/main/java/com/nextroom/nextRoomServer/repository/ThemeRepository.java
src/main/java/com/nextroom/nextRoomServer/service/ThemeService.java

feature/theme-limit → develop
- SubscriptionPlan Enum에 각 구독 플랜 별 테마 생성 제한 개수 정보를 추가하였습니다.
- 테마를 생성하기 전, 해당 유저가 구독하고 있는 플랜에 따라 테마 생성 가능 여부를 판단합니다. 최대 개수를 초과했을 경우, 예외 처리 하도록 구현하였습니다.
postman으로 api 테스트 결과 이상 없습니다!

[FEAT] 구독 플랜에 따른 테마 생성 개수 제한

---

build.gradle
src/main/java/com/nextroom/nextRoomServer/controller/HistoryController.java
src/main/java/com/nextroom/nextRoomServer/domain/HintHistory.java
src/main/java/com/nextroom/nextRoomServer/domain/PlayHistory.java
src/main/java/com/nextroom/nextRoomServer/dto/HistoryDto.java
src/main/java/com/nextroom/nextRoomServer/repository/HintHistoryRepository.java
src/main/java/com/nextroom/nextRoomServer/repository/PlayHistoryRepository.java
src/main/java/com/nextroom/nextRoomServer/security/config/SecurityConfig.java
src/main/java/com/nextroom/nextRoomServer/service/HistoryService.java

feature/analytics → develop
- 플레이 데이터를 수집하기 위해 play history API를 구현하였습니다.
- 그 외 작업 사항
- 더 이상 사용하지 않는 h2database 관련 설정을 제거하였습니다.
- Security 관련 Log 설정을 해제 하였습니다. Log의 양이 많기 때문에 이 설정은 local에서만 사용하는 게 좋아 보입니다!
postman API 테스트 결과 이상 없습니다.

[FEAT] 통계를 위한 play history API 구현

---

src/main/java/com/nextroom/nextRoomServer/security/TokenProvider.java

feature/token-expire-time → develop
- 안드로이드 테스트가 충분히 진행되었다고 합니다. 토큰 만료 시간을 원래대로 돌려 놓았습니다!
- Access Token : 1분 → 2시간
- Refresh Token : 5분 → 14일

[CHORE] 토큰 만료 시간 수정

---

src/main/java/com/nextroom/nextRoomServer/controller/HistoryController.java
src/main/java/com/nextroom/nextRoomServer/controller/PaymentController.java
src/main/java/com/nextroom/nextRoomServer/controller/SubscriptionController.java
src/main/java/com/nextroom/nextRoomServer/domain/HintHistory.java
src/main/java/com/nextroom/nextRoomServer/domain/PlayHistory.java
src/main/java/com/nextroom/nextRoomServer/domain/Shop.java
src/main/java/com/nextroom/nextRoomServer/domain/Subscription.java
src/main/java/com/nextroom/nextRoomServer/domain/Theme.java
src/main/java/com/nextroom/nextRoomServer/dto/HistoryDto.java
src/main/java/com/nextroom/nextRoomServer/dto/SubscriptionDto.java
src/main/java/com/nextroom/nextRoomServer/enums/SubscriptionPlan.java
src/main/java/com/nextroom/nextRoomServer/enums/SubscriptionStatus.java
src/main/java/com/nextroom/nextRoomServer/repository/HintHistoryRepository.java
src/main/java/com/nextroom/nextRoomServer/repository/PlayHistoryRepository.java
src/main/java/com/nextroom/nextRoomServer/service/HistoryService.java
src/main/java/com/nextroom/nextRoomServer/service/SubscriptionService.java
src/main/java/com/nextroom/nextRoomServer/service/ThemeService.java
src/main/java/com/nextroom/nextRoomServer/util/AndroidPublisherClient.java

feature/remove-subscription-analytics → develop
- 완성하지 못한 구독 결제 기능과 통계 기능을 제거합니다.
- 구독 결제의 경우, 추후 도입될 것을 가정하여 계정 생성 시 유저에 관한 구독 정보가 생성되는 부분은 주석 처리 하지 않았습니다.
postman 테스트 결과 이상 없으나, 빌드 테스트 한번 더 부탁드립니다!

[REFACTOR] 구독 결제 & 통계 기능 제거

---

build.gradle
src/main/java/com/nextroom/nextRoomServer/exceptions/StatusCode.java
src/main/java/com/nextroom/nextRoomServer/util/email/MailSender.java
src/main/resources/templates/index.html

feature/mail-html → develop
- 인증 메일 양식에 html template 적용
- 로그인 에러 문구 변경(관리자 코드 -> 이메일)
인증 메일 테스트 결과 이상 없습니다.

[FEAT] 인증 메일 html template 적용

---

src/main/java/com/nextroom/nextRoomServer/domain/Shop.java
src/main/java/com/nextroom/nextRoomServer/dto/AuthDto.java
src/main/java/com/nextroom/nextRoomServer/service/AuthService.java

feature/signup_data → develop
- 마지막 로그인 날짜를 추가 하였습니다.
- 가입 경로를 구분하기 위한 타입을 추가 하였습니다.
1: 웹(홈페이지)에서 PC로 들어온 유저
2: 웹(홈페이지)에서 모바일로 들어온 유저
3: 앱에서 들어온 유저

[FEAT] 가입 경로, 마지막 로그인 데이터 수집

---

src/main/java/com/nextroom/nextRoomServer/security/TokenProvider.java

feature/token-test → develop
- 안드로이드 테스트를 위해 토큰 만료 시간을 수정합니다
- Access Token : 2시간 → 1분
- Refresh Token : 14일 → 3분

[CHORE] 테스트를 위한 Token 만료 시간 수정

---

src/main/java/com/nextroom/nextRoomServer/security/TokenProvider.java

feature/token-expire-time → develop
- 토큰 테스트가 완료되어 토큰 시간을 돌려놓았습니다.
- 토큰 갱신에 이슈가 있어 원인을 파악하기 위해 토큰 시간을 연장하였습니다.
- Access Token : 1분 → 5시간
- Refresh Token : 5분 → 30일
클라이언트 테스트가 필요합니다.

[CHORE] Token 만료 시간 연장

---

scripts/start.sh

feature/code-deploy-variables → develop
- /etc/.profile.d/codedeploy.sh에 등록해둔 환경 변수가 작동하지 않아 AWS Parameter store를 이용하여 변수 설정을 해주었습니다.
테스트를 위해 빠른 배포가 필요합니다.

[CI/CD] CodeDeploy 환경변수 테스트

---

src/main/java/com/nextroom/nextRoomServer/controller/BannerController.java
src/main/java/com/nextroom/nextRoomServer/controller/SubscriptionController.java
src/main/java/com/nextroom/nextRoomServer/domain/Banner.java
src/main/java/com/nextroom/nextRoomServer/dto/BannerDto.java
src/main/java/com/nextroom/nextRoomServer/dto/SubscriptionDto.java
src/main/java/com/nextroom/nextRoomServer/repository/BannerRepository.java
src/main/java/com/nextroom/nextRoomServer/security/config/SecurityConfig.java
src/main/java/com/nextroom/nextRoomServer/service/BannerService.java
src/main/java/com/nextroom/nextRoomServer/service/SubscriptionService.java

feature/{banner} → develop
- 구독 요금제 조회 api 에 상세 페이지 링크 추가
- 배너 api 추가 (단일 배너)
테스트 결과를 적어주세요!

[FEAT] 배너, 구독 요금제 조회 기능 추가

---

src/main/java/com/nextroom/nextRoomServer/domain/Shop.java
src/main/java/com/nextroom/nextRoomServer/dto/HintDto.java
src/main/java/com/nextroom/nextRoomServer/dto/SubscriptionDto.java
src/main/java/com/nextroom/nextRoomServer/exceptions/StatusCode.java
src/main/java/com/nextroom/nextRoomServer/service/HintService.java

feature/image-upload → develop
- presigned url 요청 시, 구독 상태를 검증하는 로직을 추가하였습니다.
- 힌트 등록 요청 시, 구독 상태와 request의 이미지 포함 여부를 검증하는 로직을 추가하였습니다.
- 구독 상태 조회 요청 시, '구독 만료(SUBSCRIPTION_EXPIRATION)' 상태를 정확히 표현해주기 위해 response를 수정하였습니다.

[FEAT] 구독 상태 검증 로직 추가

---

src/main/java/com/nextroom/nextRoomServer/dto/SubscriptionDto.java
src/main/java/com/nextroom/nextRoomServer/exceptions/StatusCode.java
src/main/java/com/nextroom/nextRoomServer/util/inapp/AndroidPurchaseUtils.java

feature/purchase-env → develop
- RTDN의 모든 알림이 같은 구독으로 전달되더라도, 서버에서 환경을 구분하여 처리할 수 있도록 검증 로직을 추가하였습니다.
dev 서버 배포 후, 테스트 필요합니다.

[FEAT] Environment 검증 로직 추가

---

src/main/java/com/nextroom/nextRoomServer/config/FilterConfig.java
src/main/java/com/nextroom/nextRoomServer/config/InterceptorConfig.java
src/main/java/com/nextroom/nextRoomServer/config/LoggingInterceptor.java
src/main/java/com/nextroom/nextRoomServer/filter/ContentCachingLoggingFilter.java
src/main/java/com/nextroom/nextRoomServer/interceptor/LoggingInterceptor.java
src/main/java/com/nextroom/nextRoomServer/security/config/SecurityConfig.java
src/main/resources/logback-spring.xml

f/log → develop
- InterceptorConfig를 추가하였습니다.
- HttpServletRequest 인터페이스의 getInputStream() 데이터는 한 번만 읽을 수 있기 때문에 ContentCachingLoggingFilter를 추가하여 래핑하였습니다.
- getContentAsByteArray() 메서드는 캐싱된 데이터를 읽어오기 때문에 LoggingInterceptor의 preHandle이 아닌 afterCompletion에서 로그를 작성하였습니다.
- FilterConfig를 추가하여 SecurityFilter보다 CustomServletWrappingFilter가 먼저 실행될 수 있도록 설정하였습니다.
테스트 결과 로그에 잘 찍히는 걸 확인했습니다.

[FEAT] Request, Response 로그 추가

---

src/main/java/com/nextroom/nextRoomServer/controller/HintController.java
src/main/java/com/nextroom/nextRoomServer/controller/ThemeController.java
src/main/java/com/nextroom/nextRoomServer/service/ThemeService.java
src/main/java/com/nextroom/nextRoomServer/util/aws/S3Component.java

feature/timer-image → develop
- 테마 조회 api 중, 타이머 배경 이미지의 preisgned url 생성 부분 메서드를 수정하였습니다. (ForUpload -> ForDownLoad 로 변경)
(참고로 ForUpload 메서드는 업로드를 위한 presigned url 생성, ForDownLoad 메서드는 다운로드 즉 존재하는 이미지 조회를 위한 presigned url 생성 메서드입니다.)
- 타이머 배경 api 에 Swagger 설명을 추가하였습니다.

[FEAT] 타이머 이미지 기능 수정

---

src/main/java/com/nextroom/nextRoomServer/domain/Shop.java
src/main/java/com/nextroom/nextRoomServer/domain/Theme.java
src/main/java/com/nextroom/nextRoomServer/service/SubscriptionService.java
src/main/java/com/nextroom/nextRoomServer/service/ThemeService.java

feature/timer-image → develop
- 타이머 이미지 추가 시, 구독 여부에 따라 다른 active 상태로 저장
- 구독 상태일 경우, 모두 active로 저장
- 미구독 상태일 경우, 현재 저장하려는 이미지만 active, 나머지는 deacive로 저장
- 구독 상태 변경 시, 타이머 이미지 active 상태 변경
- 구독 시, 전체 타이머 이미지 active로 변경
- 구독 만료 시, 전체 타이머 이미지 deactive로 변경

[FEAT] 구독 여부에 따른 타이머 이미지 active 상태 변경
